services:
  postgres:
    image: postgres:15
    container_name: mailstash-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mailstash
      - POSTGRES_USER=mailstash
      - POSTGRES_PASSWORD=mailstash_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailstash -d mailstash"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  clamav:
    image: clamav/clamav:latest
    platform: linux/amd64
    container_name: mailstash-clamav
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav
    environment:
      - CLAMAV_NO_FRESHCLAM=false
    healthcheck:
      test: ["CMD", "clamdscan", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  postgres_data:
  clamav_data:
