version: '3.8'

services:
  clamav:
    image: clamav/clamav:latest
    container_name: mailstash-clamav
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav
    environment:
      - CLAMAV_NO_FRESHCLAM=false
    healthcheck:
      test: ["CMD", "clamdscan", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  mailstash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailstash-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
    volumes:
      - ./storage:/app/storage
      - ./dev.db:/app/dev.db
    depends_on:
      clamav:
        condition: service_healthy
    restart: unless-stopped

volumes:
  clamav_data: